markdown: rdiscount
pygments: true
paginate: 5

authors:
  ben:
    name: Ben Taitelbaum
    display_name: Ben
    gravatar: 12fb65715455bf8bac3fef388767f909
    email: ben@coshx.com
  calvin:
    name: Calvin Delamere
    display_name: Calvin
    gravatar: fea6975a1c675adb0d308dd9361eba9d
    email: calvin@coshx.com
  chielo:
    name: Chielo Zimmerman
    display_name: Chielo
    gravatar: 0538dfd35e2e8ca39dfa4d0270d8be7e
    email: chielo@coshx.com
  david:
    name: David Kapp
    display_name: Dave
    gravatar: ae4ac8fd674a4ab7d1ac5b4e8884b5aa
    email: davidkapp@coshx.com
  kovsky:
    name: David Kovsky
    display_name: David
    gravatar: 002e0e2f83c2c2193ac3f824a84c61e6
    email: david@coshx.com
  gil:
    name: Edi Gil
    display_name: gil
    gravatar: b47d4dfddf0dffcea62bd0ddd0a3840c
    email: gil@coshx.com
  gabe:
    name: Gabe Kopley
    display_name: Gabe
    gravatar: 8d0662182931f2b97a4b58feffbf067e
    email: gabe@coshx.com
  michael:
    name: Michael Makarov
    display_name: Michael
    gravatar: 8bf2ffc750cb84800bc2b992dbd19df6
    email: mikhail@coshx.com
  ryan:
    name: Ryan Ahearn
    display_name: Ryan
    gravatar: 4b5ef7e05dac60461d3710597594eacf
    email: ryan@coshx.com
  sang:
    name: Sang Won Seo
    display_name: Sang
    gravatar: 67683ef6fcce10554b34703517ec1d1d
    email: sang@coshx.com